In [1]:
import torch

In [2]:
t = torch.nn.Transformer()

/Users/handh/workspace/python/StudyTransformer/.venv/lib/python3.13/site-packages/torch/nn/modules/transformer.py:392: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


In [7]:
t(torch.randn(1,5,512), torch.randn(1,5,512)).shape

torch.Size([1, 5, 512])

In [12]:
a = torch.randn(2, 2, 10)
mask = torch.tensor([[1,0],[1,0]])
a

tensor([[[ 0.2801,  1.4756, -0.3166,  0.8744, -1.3195, -0.0589,  0.9177,
          -1.7313,  1.1677, -0.6443],
         [ 1.3228, -1.2573, -0.9463, -1.1223,  0.6768, -0.9909,  0.4107,
           1.9363,  0.1765, -1.3277]],

        [[-1.9362,  0.1259,  0.5836,  0.6182, -0.6876,  0.9177,  0.1708,
           0.5708,  1.8388, -0.2400],
         [-0.0841, -1.5050,  0.3933, -0.1127,  0.6045,  0.2396,  0.5488,
           0.1540, -0.4086, -0.8842]]])

In [13]:
a.masked_fill(mask==0, -1e9)

RuntimeError: The size of tensor a (2) must match the size of tensor b (10) at non-singleton dimension 2

In [21]:
a = torch.ones(4,4,4)

In [22]:
a.tril(diagonal=0).type(torch.bool)

tensor([[[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]],

        [[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]],

        [[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]],

        [[ True, False, False, False],
         [ True,  True, False, False],
         [ True,  True,  True, False],
         [ True,  True,  True,  True]]])

In [24]:
import math

In [54]:
position = torch.arange(0, 10).float().unsqueeze(1)

In [64]:
div_term = torch.exp(torch.arange(0, 10, 2) * -(math.log(10000.0) / 10))

In [61]:
torch.arange(0, 100, 2) * -(math.log(10000.0) / 100)

tensor([-0.0000, -0.1842, -0.3684, -0.5526, -0.7368, -0.9210, -1.1052, -1.2894,
        -1.4737, -1.6579, -1.8421, -2.0263, -2.2105, -2.3947, -2.5789, -2.7631,
        -2.9473, -3.1315, -3.3157, -3.4999, -3.6841, -3.8683, -4.0525, -4.2368,
        -4.4210, -4.6052, -4.7894, -4.9736, -5.1578, -5.3420, -5.5262, -5.7104,
        -5.8946, -6.0788, -6.2630, -6.4472, -6.6314, -6.8157, -6.9999, -7.1841,
        -7.3683, -7.5525, -7.7367, -7.9209, -8.1051, -8.2893, -8.4735, -8.6577,
        -8.8419, -9.0261])

In [56]:
position.shape

torch.Size([10, 1])

In [57]:
div_term.shape

torch.Size([5])

In [65]:
position * div_term

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04],
        [2.0000e+00, 3.1698e-01, 5.0238e-02, 7.9621e-03, 1.2619e-03],
        [3.0000e+00, 4.7547e-01, 7.5357e-02, 1.1943e-02, 1.8929e-03],
        [4.0000e+00, 6.3396e-01, 1.0048e-01, 1.5924e-02, 2.5238e-03],
        [5.0000e+00, 7.9245e-01, 1.2559e-01, 1.9905e-02, 3.1548e-03],
        [6.0000e+00, 9.5094e-01, 1.5071e-01, 2.3886e-02, 3.7857e-03],
        [7.0000e+00, 1.1094e+00, 1.7583e-01, 2.7868e-02, 4.4167e-03],
        [8.0000e+00, 1.2679e+00, 2.0095e-01, 3.1849e-02, 5.0477e-03],
        [9.0000e+00, 1.4264e+00, 2.2607e-01, 3.5830e-02, 5.6786e-03]])

In [66]:
torch.sin(position * div_term)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  1.5783e-01,  2.5116e-02,  3.9811e-03,  6.3096e-04],
        [ 9.0930e-01,  3.1170e-01,  5.0217e-02,  7.9621e-03,  1.2619e-03],
        [ 1.4112e-01,  4.5775e-01,  7.5285e-02,  1.1943e-02,  1.8929e-03],
        [-7.5680e-01,  5.9234e-01,  1.0031e-01,  1.5924e-02,  2.5238e-03],
        [-9.5892e-01,  7.1207e-01,  1.2526e-01,  1.9904e-02,  3.1548e-03],
        [-2.7942e-01,  8.1396e-01,  1.5014e-01,  2.3884e-02,  3.7857e-03],
        [ 6.5699e-01,  8.9544e-01,  1.7493e-01,  2.7864e-02,  4.4167e-03],
        [ 9.8936e-01,  9.5448e-01,  1.9960e-01,  3.1843e-02,  5.0476e-03],
        [ 4.1212e-01,  9.8959e-01,  2.2415e-01,  3.5822e-02,  5.6786e-03]])

In [26]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [29]:
-(math.log(10000.0) / 100)

-0.09210340371976183

In [28]:
math.log(10000.0)

9.210340371976184

In [32]:
math.log10(10)

1.0

In [34]:
math.exp(2)

7.38905609893065

In [36]:
math.e ** 9.2

9897.129058743903

In [38]:
math.exp(2)

7.38905609893065

In [43]:
math.log(0.5)

-0.6931471805599453

In [45]:
math.log2(0.5)

-1.0

In [47]:
a = [1,2,3,4,5,6,7,8,9]

In [53]:
a[1:5:4]

[2]

In [69]:
torch.arange(1,100, dtype=torch.int)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=torch.int32)

In [72]:
(torch.rand(1, 10, 512) * 100 % 100).type(torch.int)

tensor([[[74, 19, 39,  ..., 25, 60, 92],
         [29, 98, 96,  ..., 40,  6, 71],
         [11, 88, 47,  ..., 94, 41, 46],
         ...,
         [31, 28, 42,  ..., 57, 88, 44],
         [89, 65, 49,  ..., 62,  3, 18],
         [26, 74, 50,  ..., 89, 11, 46]]], dtype=torch.int32)