In [7]:
import csv

texts = []
with open('data/chatbot_kor/chatbot.csv', 'r', encoding='utf-8') as f:
    data = csv.reader(f)
    first_row = next(data)
    index = 0
    for row in data:

        with open(f'data/chatbot_kor/corpus/{index}.txt', 'w', encoding='utf-8') as wf:
            wf.write(row[0])
            index += 1

        with open(f'data/chatbot_kor/corpus/{index}.txt', 'w', encoding='utf-8') as wf:
            wf.write(row[1])
            index += 1
len(texts)

0

In [1]:
import glob

In [2]:
paths = [str(x) for x in glob.glob("./data/chatbot_kor/corpus/*.txt")]

In [108]:
from tokenizers import SentencePieceBPETokenizer

tokenizer = SentencePieceBPETokenizer()
tokenizer.train(paths,  vocab_size=100000, min_frequency=5, show_progress=True, special_tokens=['<unk>', '<pad>', '<bos>', '<eos>', '<mask>', '<sep>'])

encoded = tokenizer.encode("이 영화는 정말 재미있습니다.")
print(encoded.tokens)
tokenizer.save("./voca.json",True)




['▁이', '▁영화', '는', '▁정말', '▁재미있', '습니다.']


In [106]:
encoded = tokenizer.encode("안녕하세요. 반가습니다<sep>반가워요")

In [107]:
encoded.tokens

['▁안녕하세요.', '▁반가', '습니다', '<sep>', '▁반가', '워', '요']

In [127]:
import torch
criterion = torch.nn.CrossEntropyLoss(ignore_index=-100)

In [ ]:
[
    [
        [1,2,3,4],
        [5,6,7,8],
        [],
        [],
    ],
    [
        [],
        [],
        [],
        [],
    ]
]

In [ ]:
[
    [
        [1,5],
        [2,6],
        [3,7],
        [4,8],
    ],
    [
        [],
        [],
        [],
        [],
    ]
]

In [200]:
pred = torch.tensor([[
    [0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1000],
    [0,0,0,0,0,0,0,0,1],
]], dtype=torch.float)
label = torch.tensor([[
    4,
    4,
    4,
    -100,
    -100
]], dtype=torch.long)

In [201]:
pred.transpose(1,2).shape, label.shape

(torch.Size([1, 9, 5]), torch.Size([1, 5]))

In [202]:
criterion(pred.transpose(1,2), label)

tensor(2.3720)

In [179]:
a = torch.tensor([1,2,3,4,5])
b = a[1:]

In [180]:
a.a torch.tensor([1])

tensor([2, 3, 4, 5, 6])

In [175]:
b

tensor([2, 3, 4, 5])

In [171]:
a[a==1] = 10

In [172]:
a

tensor([10,  2,  3,  4,  5])